name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          server-id: github # == project.distributionManagement.repository.id. How to extract it from pom.xml?
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: 1.11.1.1413
          clj-kondo: 2023.09.07

      # optional
      - name: Cache Clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Run tests & coverage
        run: |
          clojure -X:test:coverage

      - name: Lint source
        run: |
          clj-kondo --lint src